# ----
# Site

title: POWX
description: Jekyll template for API documentation.
url: https://example.com
google_analytics_key:
permalink: pretty
baseurl:

# -----
# Build

timezone: Etc/UTC

collections:
  introduction:
    title: Introduction
    position_number: 1
  upcomingchanges:
    title: Upcoming Changes
    position_number: 2
  general:
    title: General
    position_number: 3
  profiles:
    title: Profiles
    position_number: 4
  api:
    title: API
    position_number: 5
  requests:
    title: Requests
    position_number: 6
  private:
    title: Private
    position_number: 7
  orders:
    title: Orders
    position_number: 8
  marketdata:
    title: Market Data
    position_number: 9
  products:
    title: Products
    position_number: 10
  currencies:
    title: Currencies
    position_number: 11
  websocketfeed:
    title: Websocket Feed
    position_number: 12
  overview:
    title: Overview
    position_number: 13


plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - readme.md
  - LICENSE

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      type: "documentation"
    values:
      _hide_content: true
  -
    scope:
      type: "api"
    values:
      _hide_content: true

# -----------
# CloudCannon

types:
  - get
  - put
  - delete
  - post

languages:
  bash: Bash
  c: C
  css: CSS
  html: HTML
  java: Java
  javascript: JavaScript
  json: JSON
  php: PHP
  python: Python
  ruby: Ruby

_options:
  content_markdown:
    format: p h4 h5 h6
    bold: true
    italic: true
    link: true
    bulletedlist: true
    numberedlist: true
    image: true
    table: true
    styles: /css/editor.css
